#!/usr/bin/env bash
#script displays 1-100, displays fizzbuzz when number is a multiple of 3
#and 5, displays fizz when number is multiple of 3, buzz if the number is
#multiple of 5

for (( i=1; i < 101; i++ ))
do
    if (( i % 15 == 0 )); then
	echo "FizzBuzz"
    elif (( i % 3 == 0 )); then
	echo "Fizz"
    elif (( i % 5 == 0 )); then
	echo "Buzz"
    else
	echo "$i"
    fi
done
