#!/usr/bin/env bash
#this script prints 1-20, then displays 4 then bad luck from china, 9 displays bad luck from japan, 17 displays bad luck from italy

i=1
while [ "$i" -le 20 ]
do
    echo "$i"
    case $i in
	4) echo "bad luck from China" ;;
	9) echo "bad luck from Japan" ;;
	17) echo "bad luck from Italy" ;;
    esac
    (( i++ ))
done
