#!/usr/bin/env bash
# script creates files, displays multiple texts, and deletes file

echo $$ > /var/run/myscript.pid
i=0
while [ $i -lt 1 ]
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command" ; rm -rf  /var/run/myscript.pid; exit' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm -rf /var/run/holbertonscript.pid; exit' SIGQUIT
done
