#!/usr/bin/env bash
#script displays to infinity and beyond indefinitely, i am invincible!!! when recieving sigterm signal, and sleep 2 in between each iteration

msg()
{
    echo "I am invincible!!!"
}
trap "msg" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2

done
